
<?php

/**
 * Prevents validation of decimal numbers
 * @see https://www.drupal.org/node/2230909
 */
function country_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $field_definition = $context['items']->getFieldDefinition();
  if ($field_definition->getType() == 'decimal') {
    $element['value']['#step'] = 'any';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function country_form_views_exposed_form_alter(&$form, Drupal\Core\Form\FormState $form_state, $form_id) {
  $storge = $form_state->getStorage();
  if (!empty($storge['view']) && $storge['view']->id() === 'territories') {
    $form['actions']['reset'] = array(
     '#type' => 'submit',
     '#value' => t('Reset'),
     '#submit' => array(''),
    );
    if (isset($form['actions']['submit'])) {
      $submit_id = $form['actions']['submit']['#id'];
      $form['actions']['reset']['#attributes']['onclick'] = 'javascript:jQuery(this.form).clearForm();jQuery("#' . $submit_id . '").trigger("click");return false;';
    }
  }
}
